### ISSUE TITLE
[Insight] Sensitive data should not be present in non-parameter configuration files - in app/config/security.yml, line 17

### ISSUE THREAD

**Issue by tlemesle** [tlemesle/ImieTransport#1]
**[in app/config/security.yml, line 17](https://github.com/tlemesle/ImieTransport/blob/b8719473f967287344bc6d2043529a6d4b6cac50/app/config/security.yml#L17)**

> A sensitive data has been detected in your configuration file (`password` parameter). You should consider storing it in a single parameter file.

```

     providers:
       in_memory:
         memory:
           users:
             user:  { password: userpass, roles: [ 'ROLE_USER' ] }
             admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
       fos:
        id: fos_user.user_provider.username
       all_users:
        chain:
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/fd4c5c96-1807-4baf-a598-e59f8ebc49b3/analyses/1)_
